name: CD

on:
  push:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
      - run: pnpm install --frozen-lockfile

#  lint:
#    needs: [install]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18.12.1
#          cache: 'pnpm'
#          cache-dependency-path: '**/pnpm-lock.yaml'
#      - run: pnpm run lint

  test:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
      - run: pnpm run test:cov

#  build:
#    needs: ['lint', 'test']
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18.12.1
#          cache: 'pnpm'
#          cache-dependency-path: '**/pnpm-lock.yaml'
#      - run: npm run build
#      - run: tar -cvf dist.tar ./dist
#      - uses: actions/upload-artifact@v3
#        with:
#          name: dist-${{ github.sha }}
#          path: dist.tar
#          retention-days: 30