name: CI

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  install:
    needs: [install]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 19.2.0
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile


